#on any linux server-install the appropiate ansible package
#create a directory using the command 
mkdir  ansible-playbooks
cd  ~/ansible-playbooks/
#create an ansible playbook for httpd 
vi httpd.yaml
cat httpd.yaml
- name: This sets up an httpd webserver
  hosts: WEB01
  tasks:
  - name: Install the httpd rpm  and ensure latest apache version is being installed
    yum: name=httpd state=latest
  - name: start the httpd service
    service: name=httpd state=started
  - name: Open port 80
    firewalld: service=http permanent=true state=enabled
  - name: start the firewalld service
    service: name=firewalld state=restarted
    # Disable SELinux
  - selinux:
    state: disabled
	

